[workspace]
members = [
    "bpf",
    "bpf-macros",
    "bpf-helpers",
    "bpf-helpers-sys",
    "bpf-probes",
    "bpf-utils",
    "examples/allprobes",
    "examples/allprobes/probe",
    "examples/syscount",
    "examples/syscount/probe",
]

[patch.crates-io]
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs" }
