[workspace]
members = [
    "bpf",
    "bpf-macros",
    "bpf-helpers",
    "bpf-helpers-sys",
    "bpf-probes",
    "bpf-utils",
    "examples/allprobes",
    "examples/allprobes/probe",
    "examples/rust-analysis",
    "examples/rust-analysis/hello-world",
    "examples/rust-analysis/probe",
    "examples/syscount",
    "examples/syscount/probe",
]

[patch.crates-io]
object = { path = "../object" }
