[package]
name = "stack-walker"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
findshlibs = "0.8.0"
libc = "0.2.85"
libloading = "0.7.0"

[dev-dependencies]
backtrace = "0.3.56"
