[package]
name = "bpf-backtrace"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bpf-utils = { path = "../bpf-utils" }
libc = "0.2.85"
log = "0.4.14"

[dev-dependencies]
backtrace = "0.3.56"
env_logger = "0.8.3"
