[package]
name = "syscount"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[build-dependencies]
cargo-bpf = "1.3.0"

[dependencies]
anyhow = "1.0.38"
bpf = { version = "0.1.0", path = "../../bpf" }
syscount-probe = { version = "0.1.0", path = "probe" }
