[package]
name = "rust-analysis"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[build-dependencies]
cargo-bpf = "1.3.0"

[dependencies]
anyhow = "1.0.38"
bpf = { version = "0.1.0", path = "../../bpf" }
cargo-subcommand = "0.4.10"
