[package]
name = "ehframe"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
gimli = "0.23.0"
libc = "0.2.86"
log = "0.4.14"
object = "0.23.0"
